### ISSUE TITLE
Github Actions to check tests at every commit on master?

### ISSUE THREAD

**Issue by pablooliveira** [PurplePachyderm/tensorslow#3]
If you want, it would be easy to setup a github workflow action so that your code is built and maybe checked with every commit.
You can start with the provided "C/C++ with Make" workflow and modify it to add a step installing gtest before running tests. Something like,

```
- name: install gtest
      run: sudo apt install libgtest-dev
```

**Comment by PurplePachyderm** [comment]
Should be solved by last commit

0fdd4f33beabafc830687314a58643857c6d649a

**Comment by pablooliveira** [comment]
@PurplePachyderm, that looks good !
