### ISSUE TITLE
Feedback on #4: tensor operations in autodiff

### ISSUE THREAD

**Issue by pablooliveira** [PurplePachyderm/tensorslow#5]
Congratulations for #4, this is very nice work :tada: !

One feedback: currently you encode the different types of operations (scalar, element-wise, matrix) as attribute of `Node`. This means that in some places, such as [`incrementGradient`](https://github.com/PurplePachyderm/tensorslow/blob/37c5812d0323f133bf3034950051d16d6576e66c/src/autodiff.cpp#L125) you need a `switch/case` construct.

Why did you chose this design instead of virtual methods ? I think it be possible to have `Node` as an abstract class; and implement `incrementGradient` as a virtual method. Then `ScalarNode`, `ElementWiseNode`, `MatrixNode` can inherit from `Node` and have their own version of `incrementGradient`.

What do you think ?

**Comment by PurplePachyderm** [comment]
That's a good idea, I hadn't thought about it before. I'll try to change this in a future commit.
