### ISSUE TITLE
Differentiation of matrix product causes crash when the sizes are identical

### ISSUE THREAD

**Issue by PurplePachyderm** [PurplePachyderm/tensorslow#7]
When calling the `ts::MatProdNode::incrementGradient()` method, an if statement is used to figure out the order of the operands :

https://github.com/PurplePachyderm/tensorslow/blob/24607ffd4930b0c8cac577de3706cd7647e24b19/src/autodiff.cpp#L96-L101

However, when the two matrices have the same size, one of the 2 partial derivatives will fall in case 1 while it should fall in case 2. This results in a matrice with an incorrect size, thus creating an error when incrementing the derivative in the `ts::Tensor::grad()` method.

For instance, this problem may occur when using a multilayer perceptron with two consecutives layers of the same size (thus resulting in a 1x1 matrix).

We have to find a solution to figure out in which case we are regardless of the matrices sizes.

**Comment by pablooliveira** [comment]
Dear @PurplePachyderm. That is indeed an interesting bug; good catch. I'm not sure to have grasped exactly what is going on. If you want we can organise a call so we can discuss it around the specific perceptron example.

But... my intuition is that maybe you need to store the information about the order of operands during the forward computation; so when you initially build the `ts::MatProdNode`.
What do you think ?

**Comment by PurplePachyderm** [comment]
I also think this would be a way to fix it.

Actually, I think the bug happens when : 
- A is a nxn matrix
- B is a nxm matrix
- we compute A*B, which is of size nxm

In that case, the `childDerivative` for A is the transpose of B^T, so a mxn matrix. Since A^T (`childDerivative`) has m columns and the derivative of A*B (`this->values[j]`) also has m rows, it falls in the first case. Because of it, we compute a product of (mxn) x (nxm) = (mxm) instead of (nxm) x (mxn) = (nxn).

In the perceptron example, we have exactly this case, with m=1.

I wonder if this could just be fixed by switching the order of the if statements? I'll try this, as well as storing the size of both operands in the `ts::MatProdNode`. I'm quite confident this bug can be solved relatively easily.

**Comment by pablooliveira** [comment]
I agree with your analysis.

**Comment by PurplePachyderm** [comment]
The proposed solution solved the issue !
